"""description also seeded

Revision ID: a6b22340b19d
Revises: 41a559d72caf
Create Date: 2026-08-05 14:58:00.274968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b22340b19d'
down_revision = '41a559d72caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nearby_population', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_sites', schema=None) as batch_op:
        batch_op.drop_column('nearby_population')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
